site_name: NailFec Doc
site_description: NailFec Doc
site_author: NailFec
site_url: https://nailfec.github.io/NailFecDoc/
strict: false

copyright: Copyright &copy; 2024 NailFec

theme:
  name: material
  features:
    - content.tooltips
    - navigation.tabs
    - navigation.path
    - navigation.top
    - navigation.footer
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
    - content.code.annotate
    - content.code.select
    - content.tabs.link
    - content.action.edit
    - navigation.instant
  icon:
    annotation: material/information-slab-circle
  language: zh
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: indigo
      toggle:
        icon: material/weather-night
        name: 切换为深色模式
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: 切换为浅色模式
  include_search_page: false
  search_index_only: true
  font:
    text: 'Fira Sans'
    code: 'Fira Mono'
  # favicon: 'favicon.ico'
  icon:
    logo: 'octicons/file-code-16'

# the following are copied from OI Wiki
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - md_in_html
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.superfences
  - pymdownx.tabbed:
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.critic
  - pymdownx.critic:
      mode: view
  - pymdownx.details
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - pymdownx.highlight:
      use_pygments: true
  - pymdownx.superfences
  - pymdownx.highlight:
      pygments_lang_class: true
  - pymdownx.highlight:
      auto_title: true
  - pymdownx.highlight:
      linenums: true
  - pymdownx.highlight:
      linenums_style: pymdownx-inline
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.highlight:
      line_spans: __span
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  # - pymdownx.smartsymbols # do not need
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
  - pymdownx.tabbed:
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tasklist:
      custom_checkbox: true
  - tables

markdown_extensions:
  - abbr
  - attr_list
  - pymdownx.snippets
  - admonition
  - def_list
  - footnotes
  - meta
  - toc:
      permalink: ""
      slugify: !!python/name:pymdownx.slugs.uslugify
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.highlight:
      linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.progressbar
  - pymdownx.superfences:
      custom_fences:
        - name: math
          class: arithmatex
          format: !!python/name:pymdownx.arithmatex.fence_mathjax_format
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.tabbed:
      alternate_style: true

extra_javascript:
  - javascripts/katex.js
  - https://unpkg.com/katex@0/dist/katex.min.js
  - https://unpkg.com/katex@0/dist/contrib/auto-render.min.js
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - https://unpkg.com/katex@0/dist/katex.min.css
  - stylesheets/extra.css

extra:
  disqus: 'NailFec'
  copyright: '<a href="https://github.com/NailFec/NailFecDoc/blob/main/LICENSE.md">AGPLv3 与 NailFec 附加条款</a>'
  pagetime: 'on'
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/NailFec
      name: GitHub
    - icon: fontawesome/solid/paper-plane
      link: mailto:nailfec17@gmail.com
      name: Email
  analytics:
    provider: google
    property: G-S0CCJPHNHS # measurement ID & destination ID: G-YSYNV495RP; tag ID and another destination ID: G-S0CCJPHNHS
    feedback:
      title: 为此页面的内容评价
      ratings:
        - icon: material/thumb-up-outline
          name: 此页面的内容不错
          data: 1
          note: >-
            感谢您的认可！<br>
            您也可以通过 QQ 进一步联系：<a href="https://wpa.qq.com/msgrd?V=3&Uin=3581804879">3581804879</a>
        - icon: material/thumb-down-outline
          name: 此页面的内容有待改进
          data: 0
          note: >- 
            感谢您的反馈！
            您可以发送邮件到 <a href="mailto:nailfec17@gmail.com">nailfec17@gmail.com</a> 以提供进一步的反馈。

nav:
  - NailFec Doc:
      - 首页: index.md
      # - 关于NailFec.md
      - 协议.md
      # - 免责声明.md
  - 算法笔记:
      - 模板:
          - 基本:
              - note/templates/基本/快速IO.md
              - note/templates/基本/二分.md
          - 数学:
              - note/templates/数学/检查质数.md
              - note/templates/数学/埃式筛.md
              - note/templates/数学/线性筛.md
              - note/templates/数学/扩展欧几里得.md
              - note/templates/数学/快速幂.md
              - note/templates/数学/矩阵乘法与快速幂.md
              - note/templates/数学/常系数齐次线性递推.md
              - note/templates/数学/高斯消元法.md
              - note/templates/数学/FFT乘法.md
          - 数据结构:
              - note/templates/数据结构/ST表.md
              - note/templates/数据结构/树状数组.md
              - note/templates/数据结构/线段树.md
          - 字符串:
              - note/templates/字符串/manacher.md
              - note/templates/字符串/回文自动机.md
          - 动态规划:
              - note/templates/动态规划/最长上升子序列.md
      - 算法汇总:
          - note/gather/graphtheory.md
      - 小技巧:
          - note/tricks/bitoper.md
          - note/tricks/stlusage.md
          # - note/tricks/数组的重复赋值.md
          - note/tricks/pc.md
  - 题单记录:
      - 张老师OJ:
          - 2024暑期题单:
              - 题单A:
                  - 题单记录/张老师OJ/2024暑期题单/题单A/问题A-宝藏探险.md
                  - 题单记录/张老师OJ/2024暑期题单/题单A/问题B-挑战赛.md
                  - 题单记录/张老师OJ/2024暑期题单/题单A/问题C-最长顺眼子串.md
                  - 题单记录/张老师OJ/2024暑期题单/题单A/问题D-超级弹珠.md
                  - 题单记录/张老师OJ/2024暑期题单/题单A/问题E-相邻数之和.md
                  - 题单记录/张老师OJ/2024暑期题单/题单A/问题F-蛋糕装盒.md
                  - 题单记录/张老师OJ/2024暑期题单/题单A/问题G-宇宙航行.md
              # - 题单B:
              #     - 题单记录/张老师OJ/2024暑期题单/题单B/问题A-素数间隔.md
              #     - 题单记录/张老师OJ/2024暑期题单/题单B/问题B-渔业丰收.md
              #     - 题单记录/张老师OJ/2024暑期题单/题单B/问题C-扑克牌.md
              #     - 题单记录/张老师OJ/2024暑期题单/题单B/问题D-直播获奖.md
              #     - 题单记录/张老师OJ/2024暑期题单/题单B/问题E-和为给定数.md
              #     - 题单记录/张老师OJ/2024暑期题单/题单B/问题F-数数.md
              #     - 题单记录/张老师OJ/2024暑期题单/题单B/问题G-棋盘.md
              #     - 题单记录/张老师OJ/2024暑期题单/题单B/问题H-城市导航B.md
              #     - 题单记录/张老师OJ/2024暑期题单/题单B/问题I-编辑距离.md
              #     - 题单记录/张老师OJ/2024暑期题单/题单B/问题J-扑克牌游戏.md
              # - 题单C:
              #     - 题单记录/张老师OJ/2024暑期题单/题单C/问题A-解方程.md
              #     - 题单记录/张老师OJ/2024暑期题单/题单C/问题B-狮吼总值.md
              #     - 题单记录/张老师OJ/2024暑期题单/题单C/问题C-小聪明.md
              #     - 题单记录/张老师OJ/2024暑期题单/题单C/问题D-等边三角形.md
              #     - 题单记录/张老师OJ/2024暑期题单/题单C/问题E-最大的矩形纸片.md
              #     - 题单记录/张老师OJ/2024暑期题单/题单C/问题F-最长重复子串.md
              #     - 题单记录/张老师OJ/2024暑期题单/题单C/问题G-木材仓库.md
              #     - 题单记录/张老师OJ/2024暑期题单/题单C/问题H-星座统计.md
              #     - 题单记录/张老师OJ/2024暑期题单/题单C/问题I-字符串变换2.md
              #     - 题单记录/张老师OJ/2024暑期题单/题单C/问题J-牛栏问题.md
              - 题单D:
                  - 题单记录/张老师OJ/2024暑期题单/题单D/问题A-喝汽水.md
                  - 题单记录/张老师OJ/2024暑期题单/题单D/问题B-递增序列.md
                  - 题单记录/张老师OJ/2024暑期题单/题单D/问题C-几乎是素数.md
                  - 题单记录/张老师OJ/2024暑期题单/题单D/问题D-最小公倍数的最小和.md
                  - 题单记录/张老师OJ/2024暑期题单/题单D/问题E-海克斯.md
                  - 题单记录/张老师OJ/2024暑期题单/题单D/问题F-奇怪的电梯2.md
                  - 题单记录/张老师OJ/2024暑期题单/题单D/问题G-最长回文子串B.md
                  - 题单记录/张老师OJ/2024暑期题单/题单D/问题H-交错字符串.md
                  - 题单记录/张老师OJ/2024暑期题单/题单D/问题I-三值逻辑.md
                  - 题单记录/张老师OJ/2024暑期题单/题单D/问题J-最长路径.md
              - 题单E:
                  - 题单记录/张老师OJ/2024暑期题单/题单E/问题A-评分.md
                  - 题单记录/张老师OJ/2024暑期题单/题单E/问题B-消消乐.md
                  - 题单记录/张老师OJ/2024暑期题单/题单E/问题C-机器翻译.md
                  - 题单记录/张老师OJ/2024暑期题单/题单E/问题D-插入排序.md
                  - 题单记录/张老师OJ/2024暑期题单/题单E/问题E-检索字符串.md
                  - 题单记录/张老师OJ/2024暑期题单/题单E/问题F-字符移动.md
                  - 题单记录/张老师OJ/2024暑期题单/题单E/问题G-切割绳子.md
                  - 题单记录/张老师OJ/2024暑期题单/题单E/问题H-奶牛的高度差.md
                  - 题单记录/张老师OJ/2024暑期题单/题单E/问题I-旅行.md
                  - 题单记录/张老师OJ/2024暑期题单/题单E/问题J-颜色统计.md
          - 2024上学期题单:
              - 提高研学1:
                  - 题单记录/张老师OJ/2024上学期题单/提高研学1/问题A-分析.md
                  - 题单记录/张老师OJ/2024上学期题单/提高研学1/问题B-秋游.md
                  - 题单记录/张老师OJ/2024上学期题单/提高研学1/问题C-公里数.md
                  - 题单记录/张老师OJ/2024上学期题单/提高研学1/问题D-轴对称数.md
                  - 题单记录/张老师OJ/2024上学期题单/提高研学1/问题E-整数去重.md
                  - 题单记录/张老师OJ/2024上学期题单/提高研学1/问题F-直播获奖.md
              - 提高研学2:
                  - 题单记录/张老师OJ/2024上学期题单/提高研学2/问题A-老鹰捉小鸡.md
                  - 题单记录/张老师OJ/2024上学期题单/提高研学2/问题B-有趣的3721数.md
                  - 题单记录/张老师OJ/2024上学期题单/提高研学2/问题C-第n小质数.md
                  - 题单记录/张老师OJ/2024上学期题单/提高研学2/问题D-质因数分解.md
                  - 题单记录/张老师OJ/2024上学期题单/提高研学2/问题E-分解质因数.md
                  - 题单记录/张老师OJ/2024上学期题单/提高研学2/问题F-受欢迎度调查.md
                  - 题单记录/张老师OJ/2024上学期题单/提高研学2/问题G-集训题单.md
                  - 题单记录/张老师OJ/2024上学期题单/提高研学2/问题H-数的计数.md
      - 一本通提高篇:
          - 基础算法:
              - 题单记录/一本通提高篇/基础算法/贪心算法.md
          #     - 题单记录/一本通提高篇/基础算法/二分与三分.md
          #     - 题单记录/一本通提高篇/基础算法/深搜的剪枝技巧.md
          #     - 题单记录/一本通提高篇/基础算法/广搜的优化技巧.md
          # - 字符串算法:
          #     - 题单记录/一本通提高篇/字符串算法/哈希和哈希表.md
          #     - 题单记录/一本通提高篇/字符串算法/KMP算法.md
          #     - 题单记录/一本通提高篇/字符串算法/Trie字典树.md
          #     - 题单记录/一本通提高篇/字符串算法/AC自动机.md
          # - 图论:
          #     - 题单记录/一本通提高篇/图论/最小生成树.md
          #     - 题单记录/一本通提高篇/图论/最短路.md
          #     - 题单记录/一本通提高篇/图论/SPFA算法的优化.md
          #     - 题单记录/一本通提高篇/图论/差分约束系统.md
          #     - 题单记录/一本通提高篇/图论/强连通分量.md
          #     - 题单记录/一本通提高篇/图论/割点和桥.md
          #     - 题单记录/一本通提高篇/图论/欧拉回路.md
          # - 数据结构:
          #     - 题单记录/一本通提高篇/数据结构/树状数组.md
          #     - 题单记录/一本通提高篇/数据结构/RMQ问题.md
          #     - 题单记录/一本通提高篇/数据结构/线段树.md
          #     - 题单记录/一本通提高篇/数据结构/倍增求LCA.md
          #     - 题单记录/一本通提高篇/数据结构/数链部分.md
          #     - 题单记录/一本通提高篇/数据结构/平衡树Treap.md
          # - 动态规划:
          #     - 题单记录/一本通提高篇/动态规划/区间类动态规划.md
          #     - 题单记录/一本通提高篇/动态规划/树形动态规划.md
          #     - 题单记录/一本通提高篇/动态规划/数位动态规划.md
          #     - 题单记录/一本通提高篇/动态规划/状态压缩动态规划.md
          #     - 题单记录/一本通提高篇/动态规划/单调队列优化动态规划.md
          #     - 题单记录/一本通提高篇/动态规划/斜率优化动态规划.md
          - 数学基础:
              - 题单记录/一本通提高篇/数学基础/快速幂.md
              - 题单记录/一本通提高篇/数学基础/质数.md
          #     - 题单记录/一本通提高篇/数学基础/约数.md
          #     - 题单记录/一本通提高篇/数学基础/同余问题.md
          #     - 题单记录/一本通提高篇/数学基础/矩阵乘法.md
          #     - 题单记录/一本通提高篇/数学基础/组合数学.md
          #     - 题单记录/一本通提高篇/数学基础/博弈论.md
  - 题目分享:
      - 题目分享/LOJ10008.md
      - 题目分享/UVA10382.md
      - 题目分享/最长回文子串问题.md
  - 其他:
      - 其他/NOI系列比赛配置.md
